### ISSUE TITLE
Using this BaseApp with QMake (compiling PyQtWebengine)

### ISSUE THREAD

**Issue by jurf** [flathub/io.qt.qtwebengine.BaseApp#2]
I give up, hence this issue.

This is what I have currently:

```yaml
  - name: pyqt5-webengine
    build-options:
      env:
        - QMAKEPATH=/app/lib
    config-opts:
      - --concatenate
      - --no-dist-info
      - --no-docstrings
      - --no-qsci-api
      - --no-sip-files
      - --no-stubs
      - --verbose
      - QMAKE_CFLAGS_RELEASE='-I/usr/include/python3.7m/'
      - QMAKE_CXXFLAGS_RELEASE='-I/usr/include/python3.7m/'
      - QMAKE_INCDIR+=/app/include/QtWebEngine
      - QMAKE_INCDIR+=/app/include/QtWebEngineCore
      - QMAKE_INCDIR+=/app/include/QtWebEngineWidgets
    sources:
      - type: archive
        url: https://www.riverbankcomputing.com/static/Downloads/PyQtWebEngine/5.13.2/PyQtWebEngine-5.13.2.tar.gz
        sha256: 4264911b5847c75721d8c9c30af92e58a216bd25ceef37f7abf921005c1d45a9
      - type: script
        commands:
          - processed=`sed -e 's|prefix|sysroot|' <<< $@`
          - python3 configure.py $processed
        dest-filename: configure
```

This is the closest I have got to compilation.

At first it simply failed with a `Project ERROR: Unknown module(s) in QT: webengine`. Modifying the `QMAKEPATH` fixed that, but already that is trail-and-error and I have no idea if that’s the correct solution.

Next it complained about being unable to find the include files for webengine, as it was looking for them in `/usr`. Adding the respective `QMAKE_INCDIR+=` works around that.

Now it fails with:

```
[...]
cd QtWebEngine/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /run/build/pyqt5-webengine/QtWebEngine/QtWebEngine.pro ) && make -f Makefile 
make[1]: Entering directory '/run/build/pyqt5-webengine/QtWebEngine'
g++ -c -pipe -fno-exceptions -I/usr/include/python3.7m/ -Wall -W -D_REENTRANT -fPIC -DSIP_PROTECTED_IS_PUBLIC -Dprotected=public -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I. -isystem /app/include/python3.7m -isystem /usr/include/QtWebEngine -isystem /usr/include/QtWebEngineCore -isystem /usr/include/QtQuick -isystem /usr/include/QtGui -isystem /usr/include/QtWebChannel -isystem /usr/include/QtQml -isystem /usr/include/QtNetwork -isystem /usr/include/QtPositioning -isystem /usr/include/QtCore -I. -isystem /app/include/QtWebEngine -isystem /app/include/QtWebEngineCore -isystem /app/include/QtWebEngineWidgets -I/usr/lib/mkspecs/linux-g++ -o sipQtWebEnginepart0.o sipQtWebEnginepart0.cpp
rm -f libQtWebEngine.so
g++ -Wl,--version-script=QtWebEngine.exp -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -shared -o libQtWebEngine.so sipQtWebEnginepart0.o  /usr/lib/x86_64-linux-gnu/libQt5WebEngine.so /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so /usr/lib/x86_64-linux-gnu/libQt5Quick.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5WebChannel.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Positioning.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread    
g++: error: /usr/lib/x86_64-linux-gnu/libQt5WebEngine.so: No such file or directory
g++: error: /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so: No such file or directory
make[1]: *** [Makefile:310: libQtWebEngine.so] Error 1
make[1]: Leaving directory '/run/build/pyqt5-webengine/QtWebEngine'
make: *** [Makefile:49: sub-QtWebEngine-make_first-ordered] Error 2
```

If I’m reading this correctly (and I am completely out of my league anyway), QMake still thinks WebEngine is installed in `/usr`, as `-DQT_WEBENGINE_LIB` expands into `/usr/lib/x86_64-linux-gnu/libQt5WebEngine.so`. I have no idea how to work around this.

…please help.
