### ISSUE TITLE
QtWebEngine import not found in QML

### ISSUE THREAD

**Issue by stephencomputer** [flathub/io.qt.qtwebengine.BaseApp#290]
I am attempting to package my Qt app as a flatpak.
It relies heavily on QtWebEngine, so I used this base app.

I am using qt6 with org.kde.Sdk and org.kde.Platform.
It packages successfully but then I get this error immediately when the app opens: module “QtWebEngine” plugin “qtwebenginequickplugin” not found.

The line in question is simply “import QtWebEngine” (QML).

**Comment by stephencomputer** [comment]
Here is the manifest:

```
app-id: ca.stevestudios.Swirl
runtime: org.kde.Platform
runtime-version: ‘6.5’
sdk: org.kde.Sdk
base: io.qt.qtwebengine.BaseApp
base-version: ‘6.5’
command: swirl
finish-args:

    –share=ipc
    –socket=x11
    –socket=wayland
    –filesystem=host
    –device=dri
    –env=QTWEBENGINEPROCESS_PATH=/app/bin/QtWebEngineProcess
    cleanup-commands:
    /app/cleanup-BaseApp.sh
    modules:
    name: swirl
    buildsystem: simple
    build-commands:
        install -D ca.stevestudios.Swirl.appdata.xml /app/share/metainfo/ca.stevestudios.Swirl.appdata.xml
        install -D ca.stevestudios.Swirl.desktop /app/share/applications/ca.stevestudios.Swirl.desktop
        install -D ca.stevestudios.Swirl.svg /app/share/icons/hicolor/scalable/apps/ca.stevestudios.Swirl.svg
        install -D ca.stevestudios.Swirl-symbolic.svg /app/share/icons/hicolor/symbolic/apps/ca.stevestudios.Swirl-symbolic.svg
        sources:
        type: file
        path: ca.stevestudios.Swirl.desktop
        type: file
        path: ca.stevestudios.Swirl.svg
        type: file
        path: ca.stevestudios.Swirl-symbolic.svg
        type: file
        path: ca.stevestudios.Swirl.appdata.xml
    name: swirl-bin
    buildsystem: cmake-ninja
    config-opts:
        -DCMAKE_BUILD_TYPE=Release
        sources:
        type: archive
        path: swirl-bin.tar.gz

```
